### ISSUE TITLE
sampling frequency

### ISSUE THREAD

**Issue by mikesurfline** [cedric-dufour/connectiq-app-rawlogger#2]
Hi Cedric,
great work with the app!
I was wondering, would it be possible to get accelerometer data at a higher frequency than 1Hz? 
Thanks,
Mike

**Comment by cedric-dufour** [comment]
Hi,
I believe https://github.com/cedric-dufour/connectiq-app-rawlogger/commit/a964ffa834c52384dbdd02b42f003156dfe9a19a covers your need.
