### ISSUE TITLE
Fenix 7 support

### ISSUE THREAD

**Issue by eddy-geek** [cedric-dufour/connectiq-app-rawlogger#3]
Hello,
Can you enable support for the 2022 watches? I don't think anything needs to be changed.
Thanks!

**Comment by eddy-geek** [comment]
Here is a link to my build of [RawLogger.prg](https://www.dropbox.com/s/iyv68jqzr4t4xb3/RawLogger.prg?dl=1)

@cedric-dufour if you provide your build (eg upload it to *Releases* section of the project) then people can "sideload" it to `/GARMIN/Apps` which bypasses the manifest watch list.
(whereas it does not not seem possible to get the prg from the Connect IQ website without a compatible watch)

**Comment by cedric-dufour** [comment]
> @cedric-dufour if you provide your build (eg upload it to _Releases_ section of the project) then people can "sideload" it to `/GARMIN/Apps` which bypasses the manifest watch list. (whereas it does not not seem possible to get the prg from the Connect IQ website without a compatible watch)

I don't know whether that would work. If you look at the content of the `*.iq` artefact you get after `make iq` - it's a regular zip file (IIRC) - you'll see it contains a specific `*.prg` for _each_ device (depending, I'm guessing, on their CIQ version and other device/version-specific features; e.g. glances, touch screen, etc.). In the simulator (again IIRC), using a `*.prg` built for a given device doesn't work with another one (one must rebuild when switching device). Please correct me if I'm wrong.

**Comment by eddy-geek** [comment]
Oh, maybe I'm wrong then. I'd have thought there'd be at least forward compat? Not a lot of experience here so I'm going to refrain from further stupid comments 😁
