### ISSUE TITLE
Disable step counting while recording

### ISSUE THREAD

**Issue by tjthejuggler** [cedric-dufour/connectiq-app-rawlogger#5]
Great app! I'm trying to use it to get accelerometer data to count juggling catches, but it is counting almost every throw as a step on my daily step count. Is there any way I could make it not add to my step count?

**Comment by cedric-dufour** [comment]
Updating the step count is not done by the app' itself.
I'm guessing it depends on what type of `:sport`/`:subSport` the [FIT activity is initiated with](https://github.com/cedric-dufour/connectiq-app-rawlogger/blob/v1.0.20211201a/source/RL_App.mc#L230)
This would need to be investigated

**Comment by tjthejuggler** [comment]
Yeah, I read that if it is rowing or a few other ones then it shouldn't update the step count, but I didnt see where to put that in the code. Thanks so much, it helps alot and thanks so much for making this project. I really appreciate you!
